---
#------- Development ---------#

version: '3.9'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
  backend:
    build: ./
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongodb
volumes:
  data:
#------- Production ---------#

# version: '3.9'
# services:
#   backend:
#     build: .
#     ports:
#       - '5000:5000'
#     env_file:
#       - ./.env
